/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stok;

import menu.*;
import konfigurasi.ConfigStok;
/**
 *
 * @author smaliska notebook
 */
public class Stok extends javax.swing.JFrame {

    /**
     * Creates new form TambahPenjualan
     */
    public Stok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        stok = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        ukuran = new javax.swing.JComboBox<>();
        motif = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        stokTerakhir = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        update = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        cek = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Update Harga Barang");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Motif");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Ukuran");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Harga");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Tambah Stok");

        stok.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        harga.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        ukuran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "120x200x20", "160x200x20", "180x200x20", "200x200x20" }));

        motif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        motif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polos", "Anak - Anak", "Dewasa", "Abstrak" }));
        motif.setToolTipText("");
        motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Rp.");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Biji");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("Stok Terakhir");

        stokTerakhir.setEditable(false);
        stokTerakhir.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8))
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9))
                        .addComponent(ukuran, 0, 130, Short.MAX_VALUE)
                        .addComponent(motif, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(harga, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(stokTerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(stokTerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stok, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(42, 42, 42))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        update.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        update.setText("Tambah");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        cek.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cek.setText("Check");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("&");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Tambah Stok ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void motifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_motifActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        ConfigStok s = new ConfigStok();
        if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U01";
        } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U02";
        } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U03";
        } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U04";
        } else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U01";
        }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U02";
        }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U03";
        }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U04";
        }  else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U01";
        } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U02";
        } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U03";
        } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U04";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U01";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U02";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U03";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U04";
        }
        
        s.harga = Integer.parseInt(harga.getText());
        s.stokTambah = Integer.parseInt(stok.getText());
        
        s.run();
        kosongkan();
    }//GEN-LAST:event_updateActionPerformed

    public void kosongkan(){
        harga.setText("");
        stokTerakhir.setText("");
        stok.setText("");
    }
    
    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        Menu m = new Menu();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        ConfigStok s = new ConfigStok();
        if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U01";
        } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U02";
        } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U03";
        } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M01";
            s.idUkuran = "U04";
        } else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U01";
        }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U02";
        }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U03";
        }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M02";
            s.idUkuran = "U04";
        }  else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U01";
        } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U02";
        } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U03";
        } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M03";
            s.idUkuran = "U04";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("120x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U01";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("160x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U02";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("180x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U03";
        } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("200x200x20")) {
            s.idMotif = "M04";
            s.idUkuran = "U04";
        }
        
        s.getStokCek();
        s.getHargaCek();
        harga.setText(String.valueOf(s.harga));
        stokTerakhir.setText(String.valueOf(s.stokLama));
    }//GEN-LAST:event_cekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JButton cek;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> motif;
    private javax.swing.JTextField stok;
    private javax.swing.JTextField stokTerakhir;
    private javax.swing.JComboBox<String> ukuran;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
