/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualan;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import menu.*;
import konfigurasi.*;
import print.*;
/**
 *
 * @author smaliska notebook
 */
public class Penjualan extends javax.swing.JFrame {

    ConfigPenjualan c = new ConfigPenjualan();
    DefaultTableModel model = new DefaultTableModel ();
    /**
     * Creates new form Penjualan
     */
    
    //variable tambah penjualan
    int no = 0;
    int simpanTotal;
    int totalKeseluruhan;
    
    public Penjualan() {
        initComponents();
        setTable();
    }
    
    public void setData(){
        Object[] obj = new Object[6];
            obj[0] = no;
            obj[1] = motif.getSelectedItem();
            obj[2] = ukuran.getSelectedItem();
            obj[3] = jumlah.getText();
            obj[4] = c.harga;
            obj[5] = c.total;
            model.addRow(obj);
    }
    
    public void setTable(){
        tabel.setModel(model);
        model.addColumn("No");
        model.addColumn("Motif");
        model.addColumn("Ukuran");
        model.addColumn("Qty");
        model.addColumn("Harga");
        model.addColumn("Sub Total");
        tabel.setRowHeight(35);
        tabel.setGridColor(Color.black);
        tabel.getColumnModel().getColumn(0).setPreferredWidth(40);
        tabel.getColumnModel().getColumn(1).setPreferredWidth(210);
        tabel.getColumnModel().getColumn(2).setPreferredWidth(200);
        tabel.getColumnModel().getColumn(3).setPreferredWidth(60);
        tabel.getColumnModel().getColumn(4).setPreferredWidth(100);
        tabel.getColumnModel().getColumn(5).setPreferredWidth(150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        kontak = new javax.swing.JTextField();
        enable = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        search = new javax.swing.JButton();
        print = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tambah = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        motif = new javax.swing.JComboBox<>();
        ukuran = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        enableJumlah = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Kontak");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nama ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");

        nama.setEditable(false);
        nama.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        alamat.setEditable(false);
        alamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        kontak.setEditable(false);
        kontak.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        enable.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enable.setText("Enable");
        enable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4))
                    .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enable)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kontak, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(enable))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel1.setText("Form Penjualan Sprei ");

        tabel.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total   :");

        total.setEditable(false);
        total.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        submit.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        hapus.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        hapus.setText("Delete");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cancel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        search.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        print.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(hapus)
                    .addComponent(cancel)
                    .addComponent(search)
                    .addComponent(print))
                .addGap(24, 24, 24))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Rp.");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tambah.setText("Add");
        tambah.setEnabled(false);
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Motif");

        motif.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        motif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polos", "Anak - Anak", "Dewasa", "Abstrak" }));
        motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                motifActionPerformed(evt);
            }
        });

        ukuran.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ukuran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "120x200x20", "160x200x20", "180x200x20", "200x200x20" }));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Ukuran");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("Qty");

        jumlah.setEditable(false);
        jumlah.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        enableJumlah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        enableJumlah.setText("Enable");
        enableJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enableJumlahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(motif, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(112, 112, 112)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(enableJumlah))
                    .addComponent(tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(motif, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enableJumlah))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ukuran, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void setTotal(){
        simpanTotal = c.jumlah * c.harga;
        totalKeseluruhan += simpanTotal;
    }
    
    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        if (jumlah.getText() != "" || jumlah.getText() != null) {   
            if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("120x200x20")) {
                c.idMotif = "M01";
                c.idUkuran = "U01";
                c.arrayIdMotif.add("M01");
                c.arrayIdUkuran.add("U01");
            } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("160x200x20")) {
                c.idMotif = "M01";
                c.idUkuran = "U02";
                c.arrayIdMotif.add("M01");
                c.arrayIdUkuran.add("U02");
            } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("180x200x20")) {
                c.idMotif = "M01";
                c.idUkuran = "U03";
                c.arrayIdMotif.add("M01");
                c.arrayIdUkuran.add("U03");
            } else if (motif.getSelectedItem().equals("Polos") && ukuran.getSelectedItem().equals("200x200x20")) {
                c.idMotif = "M01";
                c.idUkuran = "U04";
                c.arrayIdMotif.add("M01");
                c.arrayIdUkuran.add("U04");
            } else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("120x200x20")) {
                c.idMotif = "M02";
                c.idUkuran = "U01";
                c.arrayIdMotif.add("M02");
                c.arrayIdUkuran.add("U01");
            }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("160x200x20")) {
                c.idMotif = "M02";
                c.idUkuran = "U02";
                c.arrayIdMotif.add("M02");
                c.arrayIdUkuran.add("U02");
            }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("180x200x20")) {
                c.idMotif = "M02";
                c.idUkuran = "U03";
                c.arrayIdMotif.add("M02");
                c.arrayIdUkuran.add("U03");
            }  else if (motif.getSelectedItem().equals("Anak - Anak") && ukuran.getSelectedItem().equals("200x200x20")) {
                c.idMotif = "M02";
                c.idUkuran = "U04";
                c.arrayIdMotif.add("M02");
                c.arrayIdUkuran.add("U04");
            }  else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("120x200x20")) {
                c.idMotif = "M03";
                c.idUkuran = "U01";
                c.arrayIdMotif.add("M03");
                c.arrayIdUkuran.add("U01");
            } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("160x200x20")) {
                c.idMotif = "M03";
                c.idUkuran = "U02";
                c.arrayIdMotif.add("M03");
                c.arrayIdUkuran.add("U02");
            } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("180x200x20")) {
                c.idMotif = "M03";
                c.idUkuran = "U03";
                c.arrayIdMotif.add("M03");
                c.arrayIdUkuran.add("U03");
            } else if (motif.getSelectedItem().equals("Dewasa") && ukuran.getSelectedItem().equals("200x200x20")) {
                c.idMotif = "M03";
                c.idUkuran = "U04";
                c.arrayIdMotif.add("M03");
                c.arrayIdUkuran.add("U04");
            } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("120x200x20")) {
                c.idMotif = "M04";
                c.idUkuran = "U01";
                c.arrayIdMotif.add("M04");
                c.arrayIdUkuran.add("U01");
            } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("160x200x20")) {
                c.idMotif = "M04";
                c.idUkuran = "U02";
                c.arrayIdMotif.add("M04");
                c.arrayIdUkuran.add("U02");
            } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("180x200x20")) {
                c.idMotif = "M04";
                c.idUkuran = "U03";
                c.arrayIdMotif.add("M04");
                c.arrayIdUkuran.add("U03");
            } else if (motif.getSelectedItem().equals("Abstrak") && ukuran.getSelectedItem().equals("200x200x20")) {
                c.idMotif = "M04";
                c.idUkuran = "U04";
                c.arrayIdMotif.add("M04");
                c.arrayIdUkuran.add("U04");
            }
            
            c.getHarga();
            c.jumlah = Integer.parseInt(jumlah.getText());
            c.arrayJumlah.add(c.jumlah);
            c.setTotal();
            
            no += 1;
            setTotal();
            setData();
            total.setText(String.valueOf(totalKeseluruhan));
            jumlah.setText("");
            kosongkanJumlah();
        }
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int kolom = 0;
        int kolomTotal = 5;
        String value = null;
        String valueTotal = null;
        
        int[] baris = tabel.getSelectedRows();
        for(int i=0;i<baris.length;i++){
            value = tabel.getModel().getValueAt(baris[i], kolom).toString();
            valueTotal = tabel.getModel().getValueAt(baris[i], kolomTotal).toString();
            model.removeRow(baris[i]-i);
        }
        totalKeseluruhan -= Integer.parseInt(valueTotal);
        total.setText(String.valueOf(totalKeseluruhan));
        
        int a = Integer.parseInt(value) - 1;
        c.arrayIdMotif.remove(a);
        c.arrayIdUkuran.remove(a);
        c.arrayJumlah.remove(a);
        c.arrayHarga.remove(a);
        c.arrayTotal.remove(a);
    }//GEN-LAST:event_hapusActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        Menu m = new Menu();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void enableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableActionPerformed
        if (enable.isSelected()) {
            nama.setEditable(true);
            kontak.setEditable(true);
            alamat.setEditable(true);
        } else {
            nama.setText("");
            kontak.setText("");
            alamat.setText("");
            nama.setEditable(false);
            kontak.setEditable(false);
            alamat.setEditable(false);
        }
    }//GEN-LAST:event_enableActionPerformed

    private void motifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_motifActionPerformed

    }//GEN-LAST:event_motifActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        if (enable.isSelected() && nama.getText() != "") {
            c.namaPelanggan = nama.getText();
            c.alamatPelanggan = alamat.getText();
            c.kontakPelanggan = kontak.getText();
            SimpanVariable.namaPenerima = nama.getText();
            SimpanVariable.alamatPenerima = alamat.getText();
            SimpanVariable.kontakPenerima = kontak.getText();

            c.setHitungPelanggan();
            c.setIdPelanggan();
            c.insertPelanggan();

            kosongkanTabel();
            kosongkanPelanggan();
            kosongkanTotal();

            c.runInsert();
            kosongkanArray();
            no = 0;
        } else {
            JOptionPane.showMessageDialog(null, "Masukkan Data Pelanggan Terlebih dahulu");
        }
        
    }//GEN-LAST:event_submitActionPerformed

    private void enableJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enableJumlahActionPerformed
        if (enableJumlah.isSelected()) {
            tambah.setEnabled(true);
            jumlah.setEditable(true);
            jumlah.requestFocus();
        } else {
            tambah.setEnabled(false);
            jumlah.setEditable(false);
        }
    }//GEN-LAST:event_enableJumlahActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        CariPenjualan i = new CariPenjualan();
        this.dispose();
        i.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        DokPrint d = new DokPrint();
        this.dispose();
        d.setVisible(true);
    }//GEN-LAST:event_printActionPerformed

    public void kosongkanJumlah(){
        enableJumlah.setSelected(false);
        tambah.setEnabled(false);
        jumlah.setEditable(false);
    }
    
    public void kosongkanTotal(){
        totalKeseluruhan = 0;
        total.setText("");
    }
    
    public void kosongkanArray(){
        c.arrayIdPenjualan.clear();
        c.arrayIdMotif.clear();
        c.arrayIdUkuran.clear();
        c.arrayJumlah.clear();
        c.arrayHarga.clear();
        c.arrayTotal.clear();
    }
    
    public void kosongkanPelanggan(){
        nama.setText("");
        alamat.setText("");
        kontak.setText("");
        nama.setEditable(false);
        kontak.setEditable(false);
        alamat.setEditable(false);
        enable.setSelected(false);
    }
    
    public void kosongkanTabel(){
        int baris = model.getRowCount();
        for (int a = 0; a < baris; a++) {
            model.removeRow(0);
        }
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox enable;
    private javax.swing.JCheckBox enableJumlah;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kontak;
    private javax.swing.JComboBox<String> motif;
    private javax.swing.JTextField nama;
    private javax.swing.JButton print;
    private javax.swing.JButton search;
    private javax.swing.JButton submit;
    private javax.swing.JTable tabel;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField total;
    private javax.swing.JComboBox<String> ukuran;
    // End of variables declaration//GEN-END:variables
}
